### ISSUE TITLE
교보문고 스크레이핑하는 예제 안돌아갑니다. 사이트가 table기반에서 div기반으로 다 바뀌었어요.

### ISSUE THREAD

**Issue by anabaral** [mjh117/pyauto-textbook#1]
(모바일 웹 동일)
올해 출간한 책인데 올해 교보문고 사이트를 반영 안한 거 같은데요

**Comment by mjh117** [comment]
안녕하세요. 올해 10월에 교보문고 사이트가 개편되어 기존 소스가 돌아가지 않습니다. 개편된 사이트에 맞게 변경했으니 확인해주세요. 제보해주셔서 감사합니다!
