### ISSUE TITLE
날씨예보하는 RSS 가 바뀐 것 같습니다. 기존 url로는 지역정보만 나오고 loc태그 안에 wf태그가 없습니다

### ISSUE THREAD

**Issue by anabaral** [mjh117/pyauto-textbook#2]

**Comment by mjh117** [comment]
안녕하세요. 현재 기상청 중기 예보 RSS에 일시적인 장애가 있다고 합니다.
RSS의 URL이 바뀐 것은 아니라고 하니, 이 현상이 해결된 후에 다시 시도해보시겠어요?
제보해주셔서 감사합니다:)
